### ISSUE TITLE
sous init failure

### ISSUE THREAD

**Issue by alrs** [opentable/sous#215]
If I attempt to "sous init" inside the github-hooks directory of the ot-sous-git_deploy project, I see the following:

  (Sous)> git version
2016/11/21 15:29:13 errors.go:53: inject into *cli.SousInit target failed: getting field GDM (graph.CurrentGDM) failed: invoking graph.CurrentGDM constructor (func(*sous.State) (graph.CurrentGDM, error)) failed: getting argument 0 failed: invoking *sous.State constructor (func(graph.LocalStateReader) (*sous.State, error)) failed: error reading sous state: getting defs: Get /defs: unsupported protocol scheme ""
2016/11/21 15:29:13 errors.go:53: error reading sous state: getting defs: Get /defs: unsupported protocol scheme ""
error reading sous state: getting defs: Get /defs: unsupported protocol scheme ""

My sous config.yaml is attached as config.txt
[config.txt](https://github.com/opentable/sous/files/605064/config.txt)

**Comment by alrs** [comment]
If I attempt to "sous" init from the root of the ot-sous-git_deploy repo, sous panics:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x5250d3]

goroutine 50 [running]:
panic(0xb65800, 0xc420010100)
        /home/lars/local/src/go/src/runtime/panic.go:500 +0x1a1
github.com/opentable/sous/lib.(*State).Deployments(0x0, 0x1, 0x7fae5b4c8000, 0x0, 0x8)
        /home/lars/gopath/src/github.com/opentable/sous/lib/map_state_to_deployments.go:13 +0x73
github.com/opentable/sous/graph.newCurrentGDM(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/lars/gopath/src/github.com/opentable/sous/graph/graph.go:465 +0x2f
reflect.Value.call(0xb4f9e0, 0xca56c8, 0x13, 0xc0923d, 0x4, 0xc4204222c0, 0x1, 0x1, 0x0, 0x43436e, ...)
        /home/lars/local/src/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xb4f9e0, 0xca56c8, 0x13, 0xc4204222c0, 0x1, 0x1, 0xc420422300, 0x20, 0x18)
        /home/lars/local/src/go/src/reflect/value.go:302 +0xa4
github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe.newCtor.func1(0xc4204222c0, 0x1, 0x1, 0xc420245220, 0xc4204022a0, 0x0, 0x11e91a0, 0xbb1800)
        /home/lars/gopath/src/github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe/ctor.go:47 +0xce
github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe.(*ctor).manifest(0xc4204022a0, 0xc420245220)
        /home/lars/gopath/src/github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe/ctor.go:108 +0x21e
github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe.(*ctor).getValue.func1()
        /home/lars/gopath/src/github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe/ctor.go:80 +0x33
sync.(*Once).Do(0xc420268fd0, 0xc4204222a0)
        /home/lars/local/src/go/src/sync/once.go:44 +0xdb
created by github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe.(*ctor).getValue
        /home/lars/gopath/src/github.com/opentable/sous/vendor/github.com/samsalisbury/psyringe/ctor.go:80 +0xb5

**Comment by samsalisbury** [comment]
Thanks Lars, I'm going to try to spend some time today getting this issue (and other issues with broken commands) covered with end-to-end tests.
