### ISSUE TITLE
DI consider command line

### ISSUE THREAD

**Issue by nyarly** [opentable/sous#57]
@samsalisbury - This is mostly a thought in passing; I don't want to burn daylight on it at the moment to determine myself.

I've been noticing that a few of the commands I'm building need to construct things out of Psyringed objects because I need to consider configuration options at the time. I wonder if there's a way to incorporate arguments into the DI, so that everything could "just work" - it might well improve uniformity of interface, as well.

**Comment by samsalisbury** [comment]
I'm not sure exactly what you mean, could you send some example code of how this would look, or a link to something with a description of how it would change?

**Comment by samsalisbury** [comment]
After our conversation, I understand the issue. This should stay open, I'll add "CLI flags" as a dependency in the graph so DI can use it.
