### ISSUE TITLE
[Off topic] Hobknob support

### ISSUE THREAD

**Issue by FernandoMorais** [opentable/sous#821]
Hi all, 

Sorry about the off topic here, but since this is the most updated repo from you I wonder if you could hear my call... :)

Do you yet support, and also use, the hobknob feature flag solution? 

I'm implementing some improvements on top of it and wonder to know if I should PR them. :)

**Comment by samsalisbury** [comment]
Did you try opening an issue in https://github.com/opentable/hobknob/issues ? We are a separate team and currently unable to support hobknob, we do not use it ourselves. Maybe look for recent contributors to that repo from OpenTable and mention them by name if you're having trouble getting their attention.

**Comment by FernandoMorais** [comment]
OK! Thanks @samsalisbury !
